services:
  - type: web
    name: Kino_bot
    runtime: python3.10
    repo: https://github.com/sardor41k42/Kino_bot
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeployTrigger: commit
version: "1"